name: Deploy & Test

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying App Finished!"

  test:
    needs: deploy
    name: 'Tests'
    runs-on: ubuntu-latest
    container: 'cypress/browsers:node14.17.0-chrome91-ff89'
    steps:
      - name: 'Clone Git repo'
        uses: actions/checkout@v2

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: |
            cypress/integration/functional/**

      - name: Run Percy
        if: always()
        uses: cypress-io/github-action@v2
        with:
          command-prefix: "percy exec -- yarn"
          browser: chrome
          spec: cypress/integration/visual/**


      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Get Timestamp
        id: timestamp
        uses: nanzm/get-time-action@v1.1
        if: always()
        with:
          timeZone: 2
          format: 'YYYYMMDDHHmmss'

      - name: Generate allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: tests/functional/build/allure-results
          allure_history: allure-history
          keep_reports: 20
          github_run_num: ${{ steps.timestamp.outputs.time }}

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
